{% set name = "authlib" %}
{% set version = "1.2.0" %}
{% set sha256 = "4fa3e80883a5915ef9f5bc28630564bc4ed5b5af39812a3ff130ec76bd631e9d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|capitalize }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - requests
    - cryptography

test:
  imports:
    - authlib

about:
  home: https://github.com/lepture/authlib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The ultimate Python library in building OAuth and OpenID Connect servers. JWS,JWE,JWK,JWA,JWT included. https://authlib.org/

  doc_url: https://docs.authlib.org/en/latest/
  dev_url: https://github.com/lepture/authlib

extra:
  recipe-maintainers:
    - chrisburr
    - markfennema
