{% set name = "authlib" %}
{% set version = "1.5.1" %}
{% set sha256 = "5cbc85ecb0667312c1cdc2f9095680bb735883b123fb509fde1e65b1c5df972e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - cryptography

test:
  requires:
    - python {{ python_min }}
  imports:
    - authlib

about:
  home: https://github.com/lepture/authlib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The ultimate Python library in building OAuth and OpenID Connect servers. JWS,JWE,JWK,JWA,JWT included. https://authlib.org/

  doc_url: https://docs.authlib.org/en/latest/
  dev_url: https://github.com/lepture/authlib

extra:
  recipe-maintainers:
    - chrisburr
    - markfennema
