{% set name = "authlib" %}
{% set version = "0.15" %}
{% set sha256 = "f107574d718764b9a88528e1ce29de439dedea7307400adc4fefe960ec78d1f2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|capitalize }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - requests
    - cryptography

test:
  imports:
    - authlib

about:
  home: https://github.com/lepture/authlib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The ultimate Python library in building OAuth and OpenID Connect servers. JWS,JWE,JWK,JWA,JWT included. https://authlib.org/

  doc_url: https://docs.authlib.org/en/latest/
  dev_url: https://github.com/lepture/authlib

extra:
  recipe-maintainers:
    - chrisburr
    - markfennema
