# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "1.8.0"

package:
  name: authlib
  version: ${{ version }}

source:
  - target_directory: dist
    url: https://pypi.org/packages/source/a/authlib/authlib-${{ version }}.tar.gz
    sha256: f3ecd5f1da737262fb53bf1a4d95c4ea1ad9dd509316587a255c99ab1838a4f0
  - target_directory: src
    url: https://github.com/authlib/authlib/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 216e3085ff2b371100acbb7e8a3bfe6e403ac138dababb3346b6147c3564ca56

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - wheel
  run:
    - python >=${{ python_min }}
    - cryptography >=45.0.1
    - joserfc >=1.6.1

tests:
  - python:
      imports: authlib
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - files:
      source:
        - src/tests/
        - src/pyproject.toml
    requirements:
      run:
        - cachelib
        - django
        - flask-sqlalchemy
        - httpx <1
        - pytest-asyncio
        - pytest-django
        - pytest-env
        - python ${{ python_min }}.*
        - requests
        - starlette-full
    script:
      - cd src
      - pytest -vv --tb=long --color=yes

about:
  summary: The ultimate Python library in building OAuth and OpenID Connect servers and clients.
  license: BSD-3-Clause
  license_file: dist/LICENSE
  homepage: https://pypi.org/project/authlib
  repository: https://github.com/authlib/authlib
  documentation: https://docs.authlib.org

extra:
  recipe-maintainers:
    - chrisburr
    - markfennema
    - xylar
